compiler/natives/src/math: Implement {Cos,Sin,Tan}h.
These were implemented in pure Go before. In Go 1.8, they're now using
stubs and are implemented in assembly. This causes the following errors
in GopherJS:

	Error: runtime error: native function not implemented: math.Cosh
	Error: runtime error: native function not implemented: math.Sinh
	Error: runtime error: native function not implemented: math.Tanh

Implement them via JavaScript math object, analogous to Cos, Sin, Tan.